name: vtgm
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.7

publish_to: none

dependencies:
  nanoid: ^1.0.0
  ssr:
    git:
      url: git@github.com:Haupti/dart-ssr.git
      ref: de095de33796f1bdf4224b7a29a5d48bf55b037e # commit hash

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
